### ISSUE TITLE
Should we deprecate all the GRN stuff for now?

### ISSUE THREAD

**Issue by adamklie** [EngreitzLab/gene_network_evaluation#19]
Should we simplify the repo by branching the current main and then removing all the GRN stuff from it? This includes:

- [x] inference
- [x] evaluation
- [x] plotting

**Comment by aron0093** [comment]
I agree. It would be better if refocused this repo back on program evaluations for now.

**Comment by adamklie** [comment]
This would be fixed in this pull request: https://github.com/EngreitzLab/gene_network_evaluation/pull/35
